### ISSUE TITLE
Date not correctly processed [06_WeatherForecast.ino]

### ISSUE THREAD

**Issue by cyberman54** [RobPo/PaperiNode#6]
PaperINode Display is showing `254.65.` in line1, after succesful receiving data from node red flow.

**Comment by RobPo** [comment]
Hi @cyberman54 in the beginning I reserved only one byte for transmitting the date, and had the "dayofyear" function used to transmit and calculate the correct dd.mm format. That worked last year pretty well until somewhere in mid-august... after the 255th day of 2020 that didn't work anymore and I de-activated showing the date...
Need to think a bit about that... maybe you have an idea too? Can't easily increase the payload size for trasnmitting more date data since I need to be sure the currently running PaperiNodes still continue to run...

**Comment by cyberman54** [comment]
maybe using unix time? That would be 4 bytes total for date and time.

**Comment by RobPo** [comment]
Actually a working fix was already implemented by transmitting the day and month as one byte each (ignoring the year): 
- day: lora.RX.Data[2]
- month: lora.RX.Data[17]
Please let me know if you still see this issue.

**Comment by cyberman54** [comment]
Corrections in TTN encoder and NodeRed decoder were still missing.
Solved by https://github.com/RobPo/PaperiNode/pull/8
